# Models supporting structured output
version: "1.0.0"

# Primary section: dated model versions
dated_models:
  gpt-4o-2024-08-06:
    context_window: 128000
    max_output_tokens: 16384
    supports_structured: true
    supports_streaming: true
    supported_parameters:
      - ref: "numeric_constraints.temperature"
        max_value: null
      - ref: "numeric_constraints.top_p"
        max_value: null
      - ref: "numeric_constraints.frequency_penalty"
        max_value: null
      - ref: "numeric_constraints.presence_penalty"
        max_value: null
      - ref: "numeric_constraints.max_completion_tokens"
        max_value: null
    description: "Initial release with 16k output support"

  gpt-4o-mini-2024-07-18:
    context_window: 128000
    max_output_tokens: 16384
    supports_structured: true
    supports_streaming: true
    supported_parameters:
      - ref: "numeric_constraints.temperature"
        max_value: null
      - ref: "numeric_constraints.top_p"
        max_value: null
      - ref: "numeric_constraints.frequency_penalty"
        max_value: null
      - ref: "numeric_constraints.presence_penalty"
        max_value: null
      - ref: "numeric_constraints.max_completion_tokens"
        max_value: null
    description: "First release of mini variant"

  o1-2024-12-17:
    context_window: 200000
    max_output_tokens: 100000
    supports_structured: true
    supports_streaming: true
    supported_parameters:
      - ref: "numeric_constraints.max_completion_tokens"
        max_value: null
      - ref: "enum_constraints.reasoning_effort"
        max_value: null
    description: "Initial preview release"

  o3-mini-2025-01-31:
    context_window: 200000
    max_output_tokens: 100000
    supports_structured: true
    supports_streaming: true
    supported_parameters:
      - ref: "numeric_constraints.max_completion_tokens"
        max_value: null
      - ref: "enum_constraints.reasoning_effort"
        max_value: null
    description: "First o3-series model"

# Secondary section: aliases pointing to dated versions
aliases:
  gpt-4o: "gpt-4o-2024-08-06"
  gpt-4o-mini: "gpt-4o-mini-2024-07-18"
  o1: "o1-2024-12-17"
  o3-mini: "o3-mini-2025-01-31"
